<div id="story-popup" class="popup-large popup">
	<div class="close link"></div>
	<h2>Histoire</h2>

	<div class="popup-content">
<p>Nous voici sur Elion, immense planète verte perdue dans les étoiles peuplée par les Serdiel.
Les Serdiel sont une race très pacifique et avancée technologiquement, qui fait preuve d’une grande sagesse et ayant réussi à construire une société parfaite. A travers leurs millions d’années d’histoire, les Serdiel semblent avoir réponse à tout part leur immense savoir, mais un secret leur resta toujours inaccessible, celui de la vie. Ils y passèrent des milliers d’années, un nombre incommensurable de chercheurs poursuivirent sans cesse les travaux de leurs prédécesseurs, mais toujours en vain. Jusqu’au jour où ils réussirent enfin à toucher au but, tout du moins c’est ce qu’ils pensaient. Nul n’avait imaginé que la plus grande découverte jamais faite allée mettre fin à leur monde.</p>

<p>Une équipe de chercheurs avaient enfin réussi à canaliser ce qu’il appelait “l’énergie de la vie”, cette énergie que l’on retrouve dans toute cellule vivante. Pas plus grosse qu’une bille, ils mirent en place un système de confinement pour conserver cette énergie. La nouvelle fut rapidement propagée partout sur la planète. Les chercheurs eurent l’ordre d’intensifier leurs recherches. Mais la vie, est-elle vraiment faite pour être manipulée ? Rien n’en est plus sûr.</p>

<p>Les Serdiel appela cette période, l’ère de la grande Découverte. Mais dix ans plus tard, rien ne fut plus pareil. Après d'incessantes expériences, les chercheurs ont obtenu d’impressionnants résultats que l’on pourrait prendre pour de la magie. Développement cérébral accru, capacités surnaturelles comparables à des pouvoirs, les effets furent divers et variés en fonction des patients. Mais d’importantes divergences firent leur apparition au sein de ce peuple pourtant si soudé. Faut-il vraiment continuer ses expériences ou juste laisser la vie et l’évolution suivre son cours naturellement ?</p>

<p>Deux factions se formèrent. Les Narilë, qui soutenaient l’abandon des recherches et ainsi laisser l’évolution de leur espèce arriver naturellement. Et les Urlryn, qui voulaient maintenir les recherches à tout prix et qui devenaient frénétique à l’idée d’un pouvoir toujours plus grand.
Le feu fut mis au poudre lorsqu’un des Urlryn chercha à s’emparer de la source de vie. Face à des Urlryn qu’ils trouvaient de plus en plus dangereux, les Narilë lancèrent un amendement pour ordonner la destruction de la source de vie. Bien sûr, chaque faction vota pour les idéaux de sa faction. Mais un petit groupe qui était resté neutre et qui avait de plus en plus peur face au fanatisme grandissant des Urlryn vota en faveur de la destruction de la source de vie. C’est ainsi que la guerre civile éclata, la première guerre depuis des millénaires.</p>

<p>Les chercheurs qui avaient reçu l’ordre de détruire leurs recherches, n’en furent rien. Totalement obsédé par la source de vie, les chercheurs se rebellèrent dans leur immense station. L’armée fut rapidement déployée sur place pour mater la rébellion dans le sang. Seulement un problème de taille fit son apparition, détruire la source de vie n’était pas si simple. En plus de ne pouvoir la déplacer à cause de la complexité du matériel et du champ de confinement à maintenir en permanence pour éviter une explosion cataclysmique, la source de vie devait être déchargée progressivement enfin de préserver sa stabilité. Les Narilë se regroupèrent dans la région où se situait la station de recherche ainsi que le laboratoire contenant cette fameuse source.</p>

<p>Cinq ans plus tard, une station au aire de forteresse et entourée d’un immense champ de bataille, les Narilë commencèrent à constater l’approche de la défaite. Assiégés, épuisés, ne croyant plus à la victoire et perdant du terrain de jour en jour, l’idée de détruire d’un coup la source de vie commençait à traverser les esprits. La décision fut prise lorsque les Urlryn lancèrent toutes leurs forces pour en finir. Comme on pouvait s’y attendre, tous les fronts Narilëins s'effondrèrent. Alors que les premières forces Urlryiennes entrèrent dans la station, c’est dans une immense explosion que le champ de confinement fut rompu. Tout était blanc, nul ne pouvait ouvrir ses yeux. Alors que quasiment un quart de la surface de la planète fut rasée en quelques secondes, personne n’avait soupçonné que l’explosion ne s’était pas vraiment passé comme prévu. Au centre de l’explosion, la source de vie n’avait pas explosé mais c’était juste refermée sur elle-même avec une telle force que le dégagement d’énergie provoqua cette explosion. La source de vie se transforma en six pierres qui furent propulsée par l’explosion dans l’espace alors que la lune Linyëis de la planète passée à proximité. Les six pierres s'écrasèrent au quatre coins de Linyëis.</p>

<p>Mais les pierres furent accompagnées d’une immense vague d’énergie qui recouvrit toute la petite lune. Linyëis abritait un petit peuple d’humain bien inoffensif et encore à l’âge des chevaux, des lances et des arcs. Leur quotidien fut totalement bouleversé lorsqu’une lueur très intense envahie le ciel et vint s’écraser sur le sol avec les six pierres.</p>

<p>La vie à Linyëis fut entièrement changée en quelques instants. D’étranges créatures surgirent de la terre et des volcans. Certains humains virent leurs capacités et leur apparence physique changer. Tous ces changements si soudains provoquèrent l’anarchie. Ce n’est que quelques siècles plus tard que tout se stabilisa. Pendant ce temps, malgré la disparition de la source de vie, les Urlryns continuèrent à traquer les Narilës sans relâche à travers toute la planète jusqu’à leur extermination finale.</p>

<p>Les Serdiels avaient toujours attentivement observé l’évolution des humains sans jamais intervenir. ils avaient pris l’arrivée d’étranges créatures et les modifications de certains individus pour le résultat des résidus de radiations lors de l’explosion de la station. Jusqu’au jour où ils tombèrent sur un puissant mage qui portait autour du cou une des pierres de vie. Par son bleu unique et si perçant, nul doute possible. Et c’est ainsi que notre histoire, la guerre pour les pierres de vie commença...</p>
	</div>
</div>